### ISSUE TITLE
[Bug]: Payload is invalid

### ISSUE THREAD

**Issue by bhfish2020** [vormkracht10/filament-2fa#15]
### What happened?

Existing Laravel v11.21.0 (PHP v8.3.8) project. Issue shown below

![Image 8-24-24 at 5 37 AM](https://github.com/user-attachments/assets/49e34323-1ddf-42a9-922c-e145036b8f8d)

### How to reproduce the bug

I followed docs + added 'vendor/vormkracht10/filament-2fa/resources/dist/filament-two-factor-auth.css' to vite config. Using authenticator app. Also when I try email, it will not send. I am using aws ses, I tested email and it works

### Package Version

1.1

### PHP Version

8.3.8

### Laravel Version

11.21.10

### Which operating systems does with happen with?

macOS

### Notes

I am using Laravel valet. The 2fa secret looks encrypted in the db.

**Comment by Baspa** [comment]
Could you update to the latest version and try again? Please let me know if the issue still persist . @bhfish2020

**Comment by bhfish2020** [comment]
yes, also email was not working because my email_verified_at was null I think. Ill give it a shot

**Comment by bhfish2020** [comment]
I got it again

**Comment by Baspa** [comment]
Hmm ok, I have to take a look at it. Hopefully I have some spare time tomorrow. @bhfish2020

**Comment by Baspa** [comment]
I think I fixed it in the latest version @bhfish2020 I don't get the error anymore.
