### ISSUE TITLE
[Bug]: forgot password not found

### ISSUE THREAD

**Issue by mcube27** [vormkracht10/filament-2fa#30]
### What happened?

I use Filament 3.2.72 with an admin panel.

When I click on the forgot-password link, it doesn't find the the view to render

### How to reproduce the bug

A laravel filamentphp with an admin panel and click on Forgot password link

### Package Version

latest

### PHP Version

8.2

### Laravel Version

11

### Which operating systems does with happen with?

macOS

**Comment by Baspa** [comment]
Can you show me the exact error? Resetting the password seems to work for me @mcube27

**Comment by Baspa** [comment]
Does this error still occur? If yes, can you show me the exact error @mcube27
