### ISSUE TITLE
[Bug]: Conflict with third packages and infinite loop

### ISSUE THREAD

**Issue by akiftezcan38** [vormkracht10/filament-2fa#46]
### What happened?

When you use this package together with a password reset application, the system enters an infinite loop and booom

### Problem detail and solution

There is no problem when I use authMiddleware in this code in TwoFactorAuthPlugin.php file, but boom when I use middleware

This is the package that came out of the conflict: yebor974/filament-renew-password

`$middlewareMethod = config('filament-two-factor-auth.enabled_features.multi_tenancy') ? 'tenantMiddleware' : 'middleware';
            $panel->$middlewareMethod([
                ForceTwoFactor::class,
            ]);`

this conflicts with another middleware.this method does not allow the use of other features in the auth phase.

to

`$middlewareMethod = config('filament-two-factor-auth.enabled_features.multi_tenancy') ? 'tenantMiddleware' : 'authMiddleware';
            $panel->$middlewareMethod([
                ForceTwoFactor::class,
            ]);`

this works. (middleware => authMiddleware)

can you update this

### Package Version

1.6

### PHP Version

8.2

### Laravel Version

11

### Filament Version

3

### Which operating systems does with happen with?

Linux

### Notes

thanks

**Comment by Baspa** [comment]
Middleware that should be used in the "auth phase" should be added in the pipeline in the Fortify config. Did you try that? @akiftezcan38

**Comment by Baspa** [comment]
> Middleware that should be used in the "auth phase" should be added in the pipeline in the Fortify config. Did you try that? @akiftezcan38

If the bug still exists, can you provide me a reproduction repo with both packages installed like you just did? I'll be happy to help :) @akiftezcan38

**Comment by akiftezcan38** [comment]
> Middleware that should be used in the "auth phase" should be added in the pipeline in the Fortify config. Did you try that? @akiftezcan38

Can you share an example for this ?
Thank you @Baspa

**Comment by Baspa** [comment]
@akiftezcan38 https://laravel.com/docs/11.x/fortify#customizing-the-authentication-pipeline

**Comment by Baspa** [comment]
Any updates on this issue? @akiftezcan38
