### ISSUE TITLE
[Bug]: Attempt to read property "value" on null error

### ISSUE THREAD

**Issue by enessvg** [vormkracht10/filament-2fa#47]
### What happened?

hello, I installed the plugin and opened 2fa, then when I tried to log in, I got an error like this:
Attempt to read property “value” on null

In order to resolve this error
vendor\vormkracht10\filament-2fa\src\Http\Livewire\Auth\LoginTwoFactor.php
In line 44 $this->twoFactorType = $this->challengedUser->two_factor_type->value;
It worked when I removed the value from the code, what is this caused by? can you check?

Translated with DeepL.com (free version)

### How to reproduce the bug

Bu hatayı çözmek içinde
vendor\vormkracht10\filament-2fa\src\Http\Livewire\Auth\LoginTwoFactor.php
44. satırdaki $this->twoFactorType = $this->challengedUser->two_factor_type->value;
kodundan valueyi kaldırınca çalıştı bu neyden kaynaklanıyor? kontrol edermisiniz?

### Package Version

1.6^

### PHP Version

8.2.4

### Laravel Version

11.0.0

### Which operating systems does with happen with?

Windows

**Comment by Baspa** [comment]
Did you follow *all* the installation steps from the readme? @enessvg

**Comment by enessvg** [comment]
@Baspa Yes

**Comment by Baspa** [comment]
Can you provide me a reproduction repository? Then I'll be happy to help @enessvg

**Comment by enessvg** [comment]
I can't provide it right now, but I can leave photos like this:
![image](https://github.com/user-attachments/assets/6e98a435-d209-46b7-9767-4e05550fca6f)

Deleted value code:
`$this->twoFactorType = $this->challengedUser->two_factor_type;`

![image](https://github.com/user-attachments/assets/42496bf4-c1f7-4f3f-b7de-b9d829075a1a)


@Baspa

**Comment by Baspa** [comment]
Did you run migrations? Can you show me your user model and did you setup 2FA for the user? @enessvg

**Comment by enessvg** [comment]
> Did you run migrations? Can you show me your user model and did you setup 2FA for the user? @enessvg

Yes, I've run migrations.

User.php:
use Laravel\Fortify\TwoFactorAuthenticatable;
use Vormkracht10\TwoFactorAuth\Enums\TwoFactorType;

use HasFactory, Notifiable, HasRoles, HasPanelShield, TwoFactorAuthenticatable;

protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
            'two_factor_type' => TwoFactorType::class,
        ];
    }

**Comment by Baspa** [comment]
I just did a fresh installation here and got no errors: https://github.com/Baspa/reproduction-repo 

you can check my latest commit @enessvg

**Comment by enessvg** [comment]
OK, I will try to reinstall and try again, thanks. 

> I just did a fresh installation here and got no errors: https://github.com/Baspa/reproduction-repo
> 
> you can check my latest commit @enessvg

**Comment by Baspa** [comment]
Any updates on this issue? @enessvg

**Comment by enessvg** [comment]
@Baspa Sorry for not replying, I still haven't tried it, I will try it as soon as possible and write here

**Comment by tonypartridge** [comment]
I looked at using this package and got the same error, it would appear the casting doesn't cast null/empty two_factor_types. Ideally there should be either a default, or login if 2fa type is not set.

**Comment by Baspa** [comment]
Thanks for checking both, will try to look for a fix later today @enessvg / @tonypartridge

**Comment by tonypartridge** [comment]
Yep! Using jetsream

Many thanks
Tony

**Comment by enessvg** [comment]
> Did you guys install this package **after** already using Laravel Fortify? I guess this issue might happen when the user already has set the 2FA on their user but didn't use this package yet. Then the 2FA might be "enabled", which causes the user to be redirected to the 2FA login page, but there is no 2FA type set.
> 
> If that's the case I might need to change the documentation.
> 
> @enessvg / @tonypartridge

https://filamentphp.com/plugins/vormkracht10-2fa#installation
I followed what was said here and got that error

**Comment by Baspa** [comment]
@enessvg / @tonypartridge after I merge #49 in a few minutes you should update the package and re-run `php artisan filament-two-factor-auth:install`. 

Remove previous migration from this package before running the install command. When you run the migrations through the install command again it will now prompt if you want to update existing users to set their missing `two_factor_type`. It will default to `authenticator`.

**Comment by enessvg** [comment]
@Baspa Thank you, I'm glad I wrote this error here

**Comment by tonypartridge** [comment]
Good stuff, will review.

**Comment by tonypartridge** [comment]
only thoughts are: 

Would you like us to set the two factor type to "authenticator" for existing users? (yes/no)

should be

Would you like us to set the two factor type to "authenticator" for users that previously used 2FA in fortify? (yes/no)

**Comment by tonypartridge** [comment]
I tried this and disabled normal 2fa and then tried email but never got the email even with queue working.

**Comment by Baspa** [comment]
> only thoughts are:
> 
> Would you like us to set the two factor type to "authenticator" for existing users? (yes/no)
> 
> should be
> 
> Would you like us to set the two factor type to "authenticator" for users that previously used 2FA in fortify? (yes/no)

Feel free to submit a PR! @tonypartridge

**Comment by Baspa** [comment]
> I tried this and disabled normal 2fa and then tried email but never got the email even with queue working.

What are the exact steps you did? Have you set a `two_factor_type` on the user? Does it has its email set?
