### ISSUE TITLE
[Bug]: Attempt to read property "value" on null

### ISSUE THREAD

**Issue by MrKoopie** [vormkracht10/filament-2fa#58]
### What happened?

Authenticate with totp to Filamentphp

### How to reproduce the bug

Make sure the user has totp enabled.
Authenticate.
You will get Attempt to read property "value" on null
Related code: https://github.com/vormkracht10/filament-2fa/blob/5b37aca3f51f21129d8c5850f0cb42ca4fc3c7d0/src/Http/Livewire/Auth/LoginTwoFactor.php#L47

Suggested fix:
Replace
```
$this->twoFactorType = $this->challengedUser->two_factor_type->value;
```
with
```
$this->twoFactorType = $this->challengedUser->two_factor_type;
```

### Repository

filament-2fa

### Package Version

2.0.8

### PHP Version

8.3.13

### Laravel Version

11

### Which operating systems does with happen with?

macOS, Linux

### Notes

I'm using Laravel Sail on Mac.

**Comment by Baspa** [comment]
Fixed in #52
